"""Writes review.json for the systematic review (data only; see SKILL.md section 7 for layout)."""
import json
import os

D = "2026-10-04"
NR = "Not reported"
ABS = "[abstract only]"

protocol = {
    "question": (
        "In network intrusion detection, which Q1-journal studies combine (i) unsupervised / label-free "
        "detection of zero-day (novel) traffic, (ii) deep reinforcement learning, (iii) continual learning "
        "or drift adaptation and (iv) explainable AI, and which combinations remain unaddressed? "
        "PICO: Population = network-flow / IoT traffic datasets; Intervention = unsupervised, DRL, CL and XAI "
        "methods; Comparison = static or supervised IDS baselines; Outcome = zero-day detection and "
        "post-adaptation accuracy / F1 / FPR / forgetting. Anchor paper: GARDIAN (Sami et al., JISA 2026)."
    ),
    "ranking_rule": "Q1 journals only (SCImago SJR 2024 quartile, best category closest to the topic)",
    "inclusion": [
        "Peer-reviewed journal article in a Q1 journal (SJR 2024)",
        "2020 to present, English",
        "Proposes or evaluates an intrusion / anomaly detection method for network or vehicle-network traffic",
        "Addresses at least one of: zero-day / unknown attacks, DRL, continual learning / concept drift, XAI",
        "Reports quantitative results",
    ],
    "exclusion": [
        "Journal below Q1, or rank not verifiable",
        "Preprints (arXiv, SSRN) without a published journal version",
        "Conference papers, workshop papers, posters, book chapters, theses",
        "Surveys / reviews (used only for snowballing)",
        "Out of domain (not network/vehicle intrusion detection)",
        "Duplicates",
    ],
    "tools_used": [
        "SciSpace (search-papers)",
        "alphaXiv (discover_papers, answer_pdf_queries)",
        "WebSearch (publisher sites, SCImago lookups)",
        "WebFetch (open-access PDFs, PMC)",
        "Backward snowballing (reference lists of GARDIAN and Hossain et al. 2026)",
    ],
    "tools_unavailable": [
        "Consensus: monthly quota (30 searches) exhausted on the first call; resets 1 Nov 2026",
        "bioRxiv: not applicable (computer-security topic)",
        "SCImago and ScienceDirect pages return HTTP 403 to automated fetches; quartiles verified via "
        "search-engine snippets of the SCImago journal pages; ScienceDirect papers extracted from abstracts",
    ],
    "queries": [
        {"tool": "Consensus", "query": "deep reinforcement learning zero-day attack detection intrusion detection system (sjr_max=1)", "hits": 0, "date": D},
        {"tool": "Consensus", "query": "continual learning network intrusion detection catastrophic forgetting concept drift (sjr_max=1)", "hits": 0, "date": D},
        {"tool": "Consensus", "query": "explainable AI SHAP unsupervised anomaly detection zero-day network intrusion (sjr_max=1)", "hits": 0, "date": D},
        {"tool": "SciSpace", "query": "How has deep reinforcement learning been used to detect zero-day attacks in network intrusion detection systems?", "hits": 10, "date": D},
        {"tool": "SciSpace", "query": "How do continual learning methods prevent catastrophic forgetting in network intrusion detection under concept drift?", "hits": 10, "date": D},
        {"tool": "SciSpace", "query": "How is explainable AI (SHAP, LIME) combined with unsupervised anomaly detection for zero-day intrusion detection?", "hits": 10, "date": D},
        {"tool": "SciSpace", "query": "Which intrusion detection frameworks combine reinforcement learning with continual or incremental learning to adapt to new attacks?", "hits": 10, "date": D},
        {"tool": "SciSpace", "query": "How are pseudo-labels from clustering or autoencoder anomaly detection used to update intrusion detection models for unknown attacks without manual labeling?", "hits": 10, "date": D},
        {"tool": "SciSpace", "query": "Which studies use explainable reinforcement learning for intrusion detection or cyber defense?", "hits": 10, "date": D},
        {"tool": "alphaXiv", "query": "zero-day intrusion detection combining unsupervised anomaly detection, DRL, continual learning and explainable AI", "hits": 10, "date": D},
        {"tool": "alphaXiv", "query": "self-labeling / pseudo-labeling for adapting NIDS to drift and new attacks, explanations to validate labels or detect drift", "hits": 10, "date": D},
        {"tool": "WebSearch", "query": "deep reinforcement learning continual learning intrusion detection zero-day (sciencedirect.com)", "hits": 10, "date": D},
        {"tool": "WebSearch", "query": "explainable AI concept drift network intrusion detection continual learning IEEE Transactions (ieeexplore)", "hits": 10, "date": D},
        {"tool": "WebSearch", "query": "unsupervised zero-day attack detection explainable autoencoder SHAP Computers & Security OR ESWA", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "explainable deep reinforcement learning intrusion detection SHAP journal 2024 2025", "hits": 10, "date": D},
        {"tool": "WebSearch", "query": "semi-supervised continual learning NIDS pseudo-labels unknown attacks Computers & Security", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "explaining anomalies detected by autoencoders using SHAP ESWA", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "ExpIDS drift-adaptable NIDS explainability (publication check)", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "SOUL semi-supervised open-world continual learning NIDS (publication check)", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "Continual Learning with Strategic Selection and Forgetting (publication check)", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "explainable AI detect/explain concept drift NIDS Information Sciences / C&S / FGCS", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "reinforcement learning agent decides when to retrain intrusion detection model drift", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "zero-day attack detection unsupervised explainable KBS / JNCA / Computer Networks", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "RL-based voting feature drift-aware IDS incremental learning (publication check)", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "concept drift invariant online botnet detection heterogeneous IoT edge C&S", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "continual learning explainability intrusion detection catastrophic forgetting XAI SHAP", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "explainable reinforcement learning intrusion detection SHAP (sciencedirect.com)", "hits": 9, "date": D},
        {"tool": "WebSearch", "query": "explainable concept drift intrusion detection unsupervised drift explanation (sciencedirect.com)", "hits": 10, "date": D},
        {"tool": "WebSearch", "query": "Lopez-Martin DRL intrusion detection supervised problems ESWA", "hits": 10, "date": D},
        {"tool": "Snowballing", "query": "Reference lists of GARDIAN (JISA 2026) and Hossain et al. (ICT Express 2026)", "hits": 4, "date": D},
        {"tool": "WebSearch", "query": "18 SCImago quartile look-ups and 14 per-paper detail look-ups (not counted as identification)", "hits": 0, "date": D},
    ],
}

prisma = [
    {"stage": "Records identified: SciSpace", "count": 60},
    {"stage": "Records identified: alphaXiv", "count": 20},
    {"stage": "Records identified: WebSearch (18 topical queries)", "count": 167},
    {"stage": "Records identified: Consensus", "count": 0, "note": "quota exhausted"},
    {"stage": "Records identified: snowballing", "count": 4},
    {"stage": "Total identified", "count": 251},
    {"stage": "After de-duplication and removal of non-paper pages (metric sites, blogs, dataset pages)", "count": 150, "note": "approximate manual count"},
    {"stage": "Excluded at title/abstract: off-topic (not NIDS, or none of zero-day/DRL/CL/XAI)", "count": 93, "note": "approximate manual count"},
    {"stage": "Candidates assessed for venue rank and type", "count": 57},
    {"stage": "Excluded: preprint only (no journal version found)", "count": 13},
    {"stage": "Excluded: conference / workshop / poster / chapter", "count": 12},
    {"stage": "Excluded: journal below Q1 or rank not verifiable", "count": 6},
    {"stage": "Excluded: review / survey or out of domain", "count": 4},
    {"stage": "Included (data extracted)", "count": 22},
]


def q(clear, split, base, imb, multi, stats, code):
    return {"clear_problem": clear, "sound_split": split, "strong_baselines": base,
            "imbalance_metrics": imb, "multiple_datasets": multi, "statistics": stats, "code_data": code}


papers = [
    dict(  # 1
        title="Deep reinforcement learning for autonomous and continual network intrusion detection (GARDIAN)",
        authors="H. Sami; C. Talhi; H. Ould-Slimane; A. Mourad; H. Otrok; J. Bentahar", year=2026,
        venue="Journal of Information Security and Applications", publisher="Elsevier", quartile="Q1", sjr=0.932,
        ranking_source="SJR 2024, Computer Networks & Communications (Q1)", doi_url="https://doi.org/10.1016/j.jisa.2026.104594",
        problem="ML-based NIDS cannot adapt to new (zero-day) attack and benign patterns without labels; fine-tuning causes catastrophic forgetting; standalone DRL IDS adapts slowly.",
        objective="Two-layer autonomous CL framework: Layer 1 detects and labels emerging patterns (multi-head AE + DBSCAN + nearest-labeled-neighbour); Layer 2 uses a CGAN and a replay buffer as retraining sources, with a PPO agent deciding when and how much to fine-tune an MLP classifier.",
        method="Hybrid: unsupervised + DRL + continual learning (generative and experience replay)",
        model="Multi-head autoencoder (64-48 encoder, one decoder per class); DBSCAN (eps 0.9, min 5); CGAN (SPOCU generator); PPO (Stable-Baselines); MLP 64-128-128-64",
        dataset="NetFlow v2: NF-UNSW-NB15-v2, NF-ToN-IoT-v3, NF-BoT-IoT, NF-CSE-CIC-IDS2018 (Benign, DoS, DDoS, Reconnaissance; Bot/Infilteration/SSH-BF in sensitivity study)",
        features="NetFlow v2 flow features", labels="Labelled initial training; new traffic pseudo-labelled by Layer 1 (cluster majority / nearest labelled neighbour); optional administrator",
        threat_type="DDoS (unseen), DoS, Reconnaissance; Bot (unseen, sensitivity)",
        evaluation="Accuracy, macro-F1, DRL reward; CGAN diversity / NN distance; RL runtime and autonomy rate; ablation (CGAN+buffer / CGAN / buffer); domain- and class-incremental scenarios S1-S4",
        results="MAE flags 99% of unseen DDoS; classifier ~82% -> ~90% accuracy (CGAN-only <=85%, buffer-only <80%); PPO inference 25.47 ms; final macro-F1 0.48-0.50 in reward-sensitivity study",
        best_result="~90% accuracy after continual learning (NetFlow v2, unseen DDoS)",
        baseline="Ablation scenarios mapped to IGAN-IDS [Huang & Lei] and Prasath et al.; no external SOTA re-run",
        limitations="Authors: MAE and CGAN need fine-tuning; only MLP classifier tested; CGAN not assumed stable (diagnostics on one case). (reviewer) Pseudo-label accuracy of Layer 1 not reported; public code omits Layer 1; no XAI; single runs without variance; our reproduction on UGRansome: Layer-1 labels 82.5% correct and harmful for fine-tuning.",
        future_work="Remove manual fine-tuning of MAE and CGAN; test classifiers other than MLP",
        generalization="Unseen class (DDoS) and cross-dataset (domain-incremental) scenarios",
        real_world="Runtime of PPO and CGAN reported; autonomy rate 1.00; no deployment",
        explainability="None", reproducibility="Code on GitHub (hanisami/nids_continual_learning), but it omits Layer 1 and has no licence; data public",
        source_note="full text", quality=q(2, 1, 1, 1, 2, 0, 1)),
    dict(  # 2
        title="A Self-Adaptive Intrusion Detection System for Zero-Day Attacks Using Deep Q-Networks",
        authors="M. Alkasassbeh; E. H. Omoush; M. Almseidin; A. Aldweesh", year=2025, venue="IEEE Access", publisher="IEEE",
        quartile="Q1", sjr=0.849, ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://doi.org/10.1109/ACCESS.2025.3617792",
        problem="Signature-based IDS miss zero-day ransomware", objective="Treat flow classification as an MDP: DQN agent with asymmetric reward penalising missed ransomware",
        method="DRL (classification as RL)", model="DQN, MLP d-64-64-|A|, target network, replay buffer 1e5",
        dataset="UGRansome (149,043 flows; labels A / S / SS; 17 ransomware families)",
        features="Time, Protocol, Flag, Family, Clusters, BTC, USD, Threats (+Netflow_Bytes, Port)",
        labels="Fully labelled (reward computed from true label) despite 'no labelled data' claim",
        threat_type="Ransomware; zero-day = unseen ransomware families",
        evaluation="Accuracy, precision, recall, F1, confusion matrices; random 70/30 and zero-day family split; binary and multiclass",
        results="Binary 97.6% (random) / 95.9% (zero-day); multiclass 97.0% / 92.0%",
        best_result="95.9% accuracy, F1 0.96 (binary, zero-day family split)", baseline="Not extracted",
        limitations="(reviewer) Held-out families not listed; Family is an input feature; label-encoded categoricals make unseen families indistinguishable (our test: AE AUC 0.49); single best run reported; no code",
        future_work=NR, generalization="Unseen ransomware families (zero-day split)", real_world="Offline benchmark only",
        explainability="None", reproducibility="No code; our from-scratch reproduction: 97.7 / 93.2 / 97.6 / 93.0% (Exp 1-4)",
        source_note="full text", quality=q(2, 1, 0, 1, 0, 0, 0)),
    dict(  # 3
        title="An active learning framework using deep Q-network for zero-day attack detection",
        authors="Y. Wu; Y. Hu; J. Wang; M. Feng; A. Dong; Y. Yang", year=2024, venue="Computers & Security", publisher="Elsevier",
        quartile="Q1", sjr=1.445, ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://doi.org/10.1016/j.cose.2024.103713",
        problem="Zero-day attacks evade NIDS trained on known classes; labelling is expensive",
        objective="Active learning: DQN (with BiLSTM policy) selects zero-day samples for labelling; Euclidean-distance labelling of selected samples; CNN-BiLSTM classifier",
        method="DRL + active learning (semi-automatic labelling)", model="DQN with BiLSTM; CNN-BiLSTM classifier",
        dataset="NSL-KDD; UNSW-NB15", features="Flow features", labels="Annotator labels samples chosen by the DQN (distance-based)",
        threat_type="Withheld attack classes as zero-day", evaluation="Accuracy, F1 (zero-day classes withheld from training)",
        results="NSL-KDD acc 98.72 / F1 98.70; UNSW-NB15 acc 93.28 / F1 94.06 (as tabulated by Hossain et al. 2026)",
        best_result="F1 98.70 (NSL-KDD)", baseline="Other ML methods (abstract)",
        limitations="(secondary review, Parlanti & Catania 2025) no cross-domain evaluation; validation/test separation unclear; sequence construction not detailed",
        future_work=NR, generalization="Withheld classes within each dataset; no cross-dataset test", real_world=NR,
        explainability="None reported", reproducibility=NR, source_note=ABS + " + secondary sources", quality=q(2, 1, 1, 1, 1, 0, 0)),
    dict(  # 4
        title="AI for AI-based intrusion detection as a service: Reinforcement learning to configure models, tasks, and capacities",
        authors="Y.-D. Lin; H. Huang; D. Sudyana; Y.-C. Lai", year=2024, venue="Journal of Network and Computer Applications", publisher="Elsevier",
        quartile="Q1", sjr=1.972, ranking_source="SJR 2024 (Q1)", doi_url="https://doi.org/10.1016/j.jnca.2024.103936",
        problem="IDS-as-a-service must adapt model choice and capacity to changing traffic",
        objective="Auto-IDaS: DQN selects the ML detector per traffic condition; TD3 allocates compute capacity",
        method="DRL for IDS management (meta-level)", model="DQN (model selection); TD3 (capacity); candidate ML detectors",
        dataset=NR, features=NR, labels="Supervised detectors", threat_type="General intrusions",
        evaluation="Reward balancing F1, detection time, compute cost", results="DQN model selection raises reward 0.29-27.04%; TD3 ~5e6x faster than simulated annealing within 10% quality",
        best_result="+27.04% reward", baseline="Static model choice; simulated annealing",
        limitations=NR, future_work=NR, generalization=NR, real_world="Service-level cost and latency considered",
        explainability="None reported", reproducibility=NR, source_note=ABS, quality=q(2, 0, 1, 1, 0, 0, 0)),
    dict(  # 5
        title="Reinforcement Learning for Intrusion Detection: More Model Longness and Fewer Updates",
        authors="R. R. dos Santos; E. K. Viegas; A. O. Santin; V. V. Cogo", year=2023, venue="IEEE Transactions on Network and Service Management", publisher="IEEE",
        quartile="Q1", sjr=1.5, ranking_source="SJR 2024, Computer Networks & Communications (Q1)", doi_url="https://secplab.ppgia.pucpr.br/files/papers/2023tnsm.pdf",
        problem="ML-NIDS degrade as traffic evolves; periodic model updates are costly (labelling, compute)",
        objective="RL-formulated classifier for longer model lifespan; updates via transfer learning on a short sliding window",
        method="DRL (classification as RL) + transfer-learning updates", model="RL agent classifier; transfer-learning update with 7-day window",
        dataset="MAWIFlow: 4 years (8 TB, >7 billion flows) of real MAWI traffic, labelled by MAWILab", features="Network flow features",
        labels="MAWILab labels (unsupervised-detector consensus); updates need a labelled window", threat_type="Anomalies labelled by MAWILab",
        evaluation="Accuracy, FP and FN rates over time (quarterly / semestral)", results="Without updates ~= traditional models with semestral updates; with updates FP -8%, FN -34%, accuracy variation <=6%, ~5x less compute",
        best_result="FN -34% vs traditional updates", baseline="Traditional ML classifiers with periodic updates",
        limitations="(reviewer) Update schedule is periodic; RL does not decide when to update; no unseen-attack labelling",
        future_work=NR, generalization="Temporal: 4 years of real traffic", real_world="Real traffic, long horizon",
        explainability="None", reproducibility="MAWIFlow dataset released", source_note="full text (partial)", quality=q(2, 2, 1, 1, 0, 0, 1)),
    dict(  # 6
        title="Adaptive Defense: Zero-Day Attack Detection in NIDS With Deep Reinforcement Learning",
        authors="K. Alam; M. F. Monir; M. J. Hossain; M. S. Uddin; M. T. Habib", year=2025, venue="IEEE Access", publisher="IEEE",
        quartile="Q1", sjr=0.849, ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://ieeexplore.ieee.org/document/11063272",
        problem="NIDS fail on attack types absent from training", objective="DRL agent with stacked LSTM; attack categories excluded from training as zero-day",
        method="DRL", model="DRL agent + stacked LSTM; oversampling", dataset="NF-BoT-IoT and other NIDS datasets (DoS and Theft excluded from training in NF-BoT-IoT)",
        features="NetFlow features", labels="Fully labelled (supervised RL)", threat_type="Withheld attack categories (DoS, Theft)",
        evaluation="Accuracy, F1", results="~99% accuracy / F1 99 (as tabulated by Hossain et al. 2026)", best_result="~99% accuracy (NF-BoT-IoT)",
        baseline=NR, limitations=NR, future_work=NR, generalization="Withheld categories", real_world=NR,
        explainability="None reported", reproducibility="Code: github.com/codewithkhurshed/ZDAD", source_note=ABS + " + secondary sources", quality=q(2, 1, 0, 1, 1, 0, 2)),
    dict(  # 7
        title="Deep Q-learning intrusion detection system (DQ-IDS): A novel reinforcement learning approach for adaptive and self-learning cybersecurity",
        authors="M. A. Hossain", year=2025, venue="ICT Express", publisher="Elsevier / KICS", quartile="Q1", sjr=1.009,
        ranking_source="SJR 2024, Computer Networks & Communications (Q1)", doi_url="https://www.sciencedirect.com/science/article/pii/S2405959525000694",
        problem="Static IDS fail on evolving attacks", objective="DQN classifier with experience replay and adaptive epsilon-greedy",
        method="DRL", model="DQN", dataset="CICIoT2023", features="Flow features", labels="Fully labelled (reward from labels)",
        threat_type="IoT attacks", evaluation="Accuracy, FP/FN", results="97.18% accuracy on CICIoT2023", best_result="97.18% accuracy",
        baseline=NR, limitations=NR, future_work=NR, generalization=NR, real_world=NR, explainability="None reported", reproducibility=NR,
        source_note=ABS, quality=q(1, 0, 0, 1, 0, 0, 0)),
    dict(  # 8
        title="A cross-dataset based zero-day intrusion detection system by integrating siamese network and reinforcement learning",
        authors="Md. M. Hossain; S. D. Turja; S. Tasnim; Md. F.-U.-A. Juboraj; M. I. Hossain", year=2026, venue="ICT Express", publisher="Elsevier / KICS",
        quartile="Q1", sjr=1.009, ranking_source="SJR 2024, Computer Networks & Communications (Q1)", doi_url="https://www.sciencedirect.com/science/article/pii/S2405959526000731",
        problem="IoT zero-day attacks; high false positives of anomaly IDS",
        objective="Unsupervised anomaly detection on two datasets, Siamese cross-dataset distance filtering of novel anomalies, PPO agent for adaptive response",
        method="Unsupervised + DRL", model="PCA / AE / IForest / OC-SVM / K-means; Siamese network; PPO (vs DQN, SAC)",
        dataset="CICIoT2023 + CIC-BCCC-NRC-TabularIoTAttacks-2024 (~20 shared features)", features="CICFlowMeter flow features",
        labels="Unsupervised detection; RL reward +1/-1 from labels; zero-day ground truth = 80th-percentile distance threshold",
        threat_type="IoT DDoS/DoS/Recon/web/Mirai; withheld classes", evaluation="Accuracy, F1, zero-day detection rate, FPR, ROC-AUC, latency, ANOVA over hyper-parameters",
        results="Unseen accuracy 99.07%, zero-day detection 93.94%, FPR 2.21%, AUC 0.997, 0.5 ms/sample",
        best_result="93.94% zero-day detection rate", baseline="DQN, SAC; literature tables (not re-run)",
        limitations="Authors: PPO is a black box (not interpretable); data quality; retraining needed; 77 min training. (reviewer) Siamese distance AUC ~0.50; zero-day labels defined by the distance threshold itself",
        future_work="Adversarial testing; XAI (attention, SHAP); GAN synthetic data; online learning to prevent forgetting; federated learning",
        generalization="Cross-dataset (two CIC IoT datasets) and withheld classes", real_world="Latency and memory reported",
        explainability="None (listed as future work)", reproducibility=NR, source_note="full text (arXiv version)", quality=q(2, 1, 1, 2, 2, 1, 0)),
    dict(  # 9
        title="ULTIMATE: A Multi-Agent Deep Reinforcement Learning Framework for false-positive optimized enterprise intrusion detection",
        authors="S. Saidane; F. Telch; K. Shahin; P. Gkonis; F. Granelli", year=2026, venue="Array", publisher="Elsevier",
        quartile="Q1", sjr=1.016, ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://www.sciencedirect.com/science/article/pii/S2590005626002195",
        problem="DRL IDS trade precision for recall; high false-positive rates",
        objective="Three topology-aware DRL agents (core router, cloud gateway, IoT segment) with false-positive-constrained reward (-10 per false alarm) and dynamic thresholds",
        method="Multi-agent DRL + XAI", model="Multi-agent DRL; SHAP", dataset="IoT Network Intrusion Dataset",
        features="Flow features", labels="Labelled (reward from labels)", threat_type="DDoS, port scan, exfiltration, malware C2, IoT compromise, zero-day",
        evaluation="Accuracy, recall, FPR, F1 per scenario, latency, throughput",
        results="90.7% accuracy, 94.6% recall, 13.3% FPR; zero-shot scenarios F1 80.8-92.0%; <5 ms, 72K flows/s",
        best_result="F1 92.0% (best zero-shot scenario)", baseline="Single-agent DRL; transformer-based IDS",
        limitations=NR, future_work=NR, generalization="Zero-shot across six attack scenarios", real_world="Latency / throughput reported",
        explainability="SHAP-based explanations integrated", reproducibility=NR, source_note=ABS, quality=q(2, 1, 1, 2, 0, 0, 0)),
    dict(  # 10
        title="Adaptive intrusion detection in industrial internet of things using deep reinforcement learning against advanced persistent threat attacks",
        authors="Not retrieved (paywalled page)", year=2026, venue="Engineering Applications of Artificial Intelligence", publisher="Elsevier",
        quartile="Q1", sjr=1.652, ranking_source="SJR 2024 (Q1)", doi_url="https://www.sciencedirect.com/science/article/abs/pii/S0952197626018336",
        problem="Static IIoT IDS need full retraining under concept drift and multi-stage APTs",
        objective="DRL-GCN: GCN captures device topology; DQN updates the detection policy online from state-action-reward transitions",
        method="DRL + graph learning (online adaptation)", model="DQN + GCN", dataset=NR, features="Device-interaction graph + traffic features",
        labels="Reward from labels (supervised RL)", threat_type="APT / multi-stage attacks in IIoT", evaluation=NR, results=NR, best_result=NR,
        baseline="Static models (abstract)", limitations=NR, future_work=NR, generalization="Concept drift / previously unknown threats (claimed)",
        real_world="Online adaptation", explainability="None reported", reproducibility=NR, source_note=ABS, quality=q(1, 0, 0, 0, 0, 0, 0)),
    dict(  # 11
        title="IGPC-MSOS: A knowledge-preserving transfer learning framework with dynamic mode-switching for handling concept drift in network intrusion detection systems",
        authors="M. A. Shyaa; N. F. Ibrahim; Z. Zainol; R. Abdullah; M. Anbar; L. Alzubaidi", year=2026, venue="Knowledge-Based Systems", publisher="Elsevier",
        quartile="Q1", sjr=1.934, ranking_source="SJR 2024, Artificial Intelligence (Q1)", doi_url="https://doi.org/10.1016/j.knosys.2026.115361",
        problem="Concept drift degrades IDS; fragmented drift handling and weak knowledge retention",
        objective="Mode-switching combiner over OSELM / FA-OSELM / KP-OSELM selected by drift detection and performance feedback",
        method="Online / continual learning with drift detection", model="OSELM variants + incremental genetic programming combiner",
        dataset="Five benchmark IDS datasets", features=NR, labels="Labelled stream", threat_type="General intrusions",
        evaluation="Recall, F1, inference latency", results="Recall 96-100%; F1 0.96-0.9995; latency <2 ms", best_result="F1 0.9995",
        baseline="FlowTransformer; ATNN", limitations=NR, future_work=NR, generalization="Drifting streams on 5 datasets",
        real_world="Low latency", explainability="None reported", reproducibility=NR, source_note=ABS, quality=q(2, 1, 1, 1, 2, 0, 0)),
    dict(  # 12
        title="Reinforcement Learning-Based Voting for Feature Drift-Aware Intrusion Detection: An Incremental Learning Framework",
        authors="Not retrieved", year=2025, venue="IEEE Access", publisher="IEEE", quartile="Q1", sjr=0.849,
        ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://ieeexplore.ieee.org/document/10896652",
        problem="Feature drift (changing feature relevance) in streaming IDS", objective="IFDA-GPC with VE-DQN-MAFS: multi-agent DQN feature selection with voting inside an incremental GP combiner",
        method="DRL (feature selection) + incremental learning", model="Voting-enhanced DQN multi-agent feature selection; GP combiner",
        dataset="KDD Cup'99, CICIDS-2017, HIKARI-2021, ISCX2012", features="Dynamic feature subsets", labels="Labelled stream",
        threat_type="General intrusions", evaluation="Accuracy (evolving and non-evolving scenarios)", results="93% accuracy on CICIDS-2017 (GPC-KOS-DFS)",
        best_result="93% accuracy (CICIDS-2017)", baseline="Existing incremental methods", limitations=NR, future_work=NR,
        generalization="Evolving feature scenarios", real_world=NR, explainability="None reported", reproducibility=NR, source_note=ABS, quality=q(2, 1, 1, 0, 2, 0, 0)),
    dict(  # 13
        title="Analysis of Continual Learning Models for Intrusion Detection System",
        authors="S. Prasath; K. Sethi; D. Mohanty; P. Bera; S. R. Samantaray", year=2022, venue="IEEE Access", publisher="IEEE",
        quartile="Q1", sjr=0.849, ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://doi.org/10.1109/ACCESS.2022.3222715",
        problem="DNN IDS forget old knowledge under covariate shift and zero-day attacks", objective="Eight-stage drift-analysis framework and comparison of CL methods",
        method="Continual learning", model="Learning without Forgetting, Experience Replay, Dark Experience Replay (MLP heads)",
        dataset="NSL-KDD; CICIDS2017", features="Flow features", labels="Fully labelled", threat_type="General intrusions",
        evaluation="Accuracy, macro-F1, forgetting, FPR, FNR", results="CL models improve accuracy and lower FPR vs prior work", best_result=NR,
        baseline="State-of-the-art (unspecified in abstract)", limitations=NR, future_work=NR, generalization="Incremental tasks within datasets",
        real_world=NR, explainability="None", reproducibility=NR, source_note=ABS, quality=q(2, 1, 1, 2, 1, 0, 0)),
    dict(  # 14
        title="RepShield: Robust knowledge representation in continual learning for network intrusion detection",
        authors="Y. Liu; W. Niu; H. Li; M. He; X. Ding; J. Gong; R. Yan; Z. Li; X. Zhang", year=2026, venue="Computer Networks", publisher="Elsevier",
        quartile="Q1", sjr=1.17, ranking_source="SJR 2024, Computer Networks & Communications (Q1)", doi_url="https://www.sciencedirect.com/science/article/abs/pii/S1389128626003208",
        problem="CL methods do not decouple new learning from knowledge retention at the gradient level",
        objective="Gradient projection onto the orthogonal complement of a historical feature subspace, PCA-based drift detection, strategic buffer selection",
        method="Continual learning", model="Gradient projection memory; PCA drift detector; replay buffer", dataset="NSL-KDD; UNSW-NB15",
        features="Flow features", labels="Labelled tasks", threat_type="General intrusions", evaluation="F1 (incremental and cross-distribution tasks)",
        results="Peak F1 91.67% (incremental) and 93.93% (cross-distribution)", best_result="F1 93.93%", baseline="SOTA CL methods",
        limitations=NR, future_work=NR, generalization="Cross-distribution tasks", real_world=NR, explainability="None reported", reproducibility=NR,
        source_note=ABS, quality=q(2, 1, 1, 1, 1, 0, 0)),
    dict(  # 15
        title="Latent space alignment for robust detection of IoT botnet attacks in non-stationary environments",
        authors="H. Wasswa; H. A. Abbass; T. Lynar", year=2025, venue="Knowledge-Based Systems", publisher="Elsevier", quartile="Q1", sjr=1.934,
        ranking_source="SJR 2024, Artificial Intelligence (Q1)", doi_url="https://www.sciencedirect.com/science/article/pii/S0950705125017873",
        problem="IoT attack drift forces frequent retraining and forgetting", objective="VAE latent space learned on history; new data aligned to it so the classifier needs no retraining",
        method="Representation learning (VAE) for drift robustness", model="VAE + latent-space classifier + alignment", dataset="N-BaIoT (10 classes)",
        features="IoT traffic statistics", labels="Labelled historical data; alignment unlabelled", threat_type="IoT botnet (Mirai, Gafgyt)",
        evaluation="Accuracy", results="99.52% accuracy (N-BaIoT, 10 classes)", best_result="99.52% accuracy", baseline="Methods 3.2-16.07 pts lower",
        limitations=NR, future_work=NR, generalization="Non-stationary traffic", real_world="Avoids retraining", explainability="None reported",
        reproducibility="Preprint on SSRN", source_note=ABS, quality=q(2, 1, 1, 0, 0, 0, 0)),
    dict(  # 16
        title="VLSA-CL: A variational latent space alignment and contrastive learning framework for robust detection of IoT botnet attacks under concept drift",
        authors="H. Wasswa; H. A. Abbass; T. Lynar", year=2026, venue="Neurocomputing", publisher="Elsevier", quartile="Q1", sjr=1.471,
        ranking_source="SJR 2024, Artificial Intelligence (Q1)", doi_url="https://www.sciencedirect.com/science/article/pii/S0925231226014967",
        problem="Abrupt concept drift in IoT botnet traffic degrades static detectors", objective="VAE latent alignment + contrastive learning; classifier trained once",
        method="Representation learning (VAE, contrastive) for drift robustness", model="VAE + contrastive loss + classifier", dataset="Three real-world IoT attack datasets",
        features="IoT traffic features", labels="Labelled historical data", threat_type="IoT botnet", evaluation="False alarms, missed detections on unseen traffic",
        results="Sustains detection under drift with fewer false alarms / misses (abstract)", best_result=NR, baseline=NR, limitations=NR, future_work=NR,
        generalization="Abrupt drift, unseen traffic", real_world="No retraining", explainability="None reported", reproducibility="Preprint on SSRN",
        source_note=ABS, quality=q(2, 1, 0, 1, 2, 0, 0)),
    dict(  # 17
        title="Class imbalance and concept drift invariant online botnet threat detection framework for heterogeneous IoT edge",
        authors="Nitish A; Hanumanthappa J; S. P. Shiva Prakash; K. Krinkin", year=2024, venue="Computers & Security", publisher="Elsevier",
        quartile="Q1", sjr=1.445, ranking_source="SJR 2024, Computer Science (misc.) (Q1)", doi_url="https://www.sciencedirect.com/science/article/abs/pii/S0167404824001214",
        problem="Botnet zero-day attacks on heterogeneous IoT edge; scarce labels and class imbalance", objective="ONIDS: device-specific online NID with Beta-distribution inference and ELMO online retraining",
        method="Online learning with drift adaptation", model="Beta-distribution traffic inference; ELMO online identification", dataset=NR,
        features="Device-specific traffic", labels="Online retraining with labels", threat_type="IoT botnets (zero-day)", evaluation=NR, results=NR, best_result=NR,
        baseline=NR, limitations=NR, future_work=NR, generalization="Drift categories in heterogeneous IoT", real_world="Low memory / compute for edge",
        explainability="None reported", reproducibility=NR, source_note=ABS, quality=q(2, 0, 0, 1, 0, 0, 0)),
    dict(  # 18
        title="An adaptable deep learning-based intrusion detection system to zero-day attacks",
        authors="M. Soltani; B. Ousat; M. Jafari Siavoshani; A. H. Jahangir", year=2023, venue="Journal of Information Security and Applications", publisher="Elsevier",
        quartile="Q1", sjr=0.932, ranking_source="SJR 2024, Computer Networks & Communications (Q1)", doi_url="https://doi.org/10.1016/j.jisa.2023.103516",
        problem="Closed-set IDS cannot recognise new attacks", objective="Open-set recognition (DOC++) flags unknown samples; novel samples are clustered on deep features for later model update",
        method="Open-set / novelty detection + clustering", model="DOC++ deep novelty classifier + clustering on deep layer", dataset=NR,
        features="Deep features of traffic", labels="Labelled known classes; unknown samples clustered (expert labels clusters)", threat_type="Unknown attacks",
        evaluation=NR, results=NR, best_result=NR, baseline=NR, limitations=NR, future_work=NR, generalization="Unknown attack classes",
        real_world=NR, explainability="None reported", reproducibility=NR, source_note=ABS, quality=q(2, 1, 0, 0, 0, 0, 0)),
    dict(  # 19
        title="An intelligent zero-day attack detection system using unsupervised machine learning for enhancing cyber security",
        authors="A. Jain; R. Bagoria; P. Arora", year=2025, venue="Knowledge-Based Systems", publisher="Elsevier", quartile="Q1", sjr=1.934,
        ranking_source="SJR 2024, Artificial Intelligence (Q1)", doi_url="https://doi.org/10.1016/j.knosys.2025.113833",
        problem="Zero-day attacks in IoT networks", objective="ZdAD-UML: HOA feature selection, enhanced K-means weighted autoencoder features, multi-layer detection (GNN / LightGBM+SHAP / CAE+CNN)",
        method="Unsupervised + XAI", model="Hippopotamus optimisation; EKC-WCAE; spatio-temporal GNN; LightGBM; contractive AE + CNN; SHAP",
        dataset=NR, features="Network flow + host + memory features", labels="Unsupervised feature learning; supervised layers", threat_type="IoT zero-day attacks",
        evaluation=NR, results=NR, best_result=NR, baseline=NR, limitations=NR, future_work=NR, generalization="Zero-day (claimed)", real_world=NR,
        explainability="SHAP on the host-layer LightGBM", reproducibility=NR, source_note=ABS, quality=q(1, 0, 0, 0, 0, 0, 0)),
    dict(  # 20
        title="Semi-supervised intrusion detection system for in-vehicle networks based on variational autoencoder and adversarial reinforcement learning",
        authors="T.-P. Nguyen; J. Cho; D. Kim", year=2024, venue="Knowledge-Based Systems", publisher="Elsevier", quartile="Q1", sjr=1.934,
        ranking_source="SJR 2024, Artificial Intelligence (Q1)", doi_url="https://doi.org/10.1016/j.knosys.2024.112563",
        problem="In-vehicle (CAN) IDS need many labels and miss unknown attacks", objective="VAE pre-training with pseudo-labelling plus adversarial RL agents that classify and select samples",
        method="Semi-supervised (unsupervised VAE + pseudo-labels) + adversarial DRL", model="VAE; adversarial RL agents", dataset="In-vehicle CAN datasets",
        features="CAN frames", labels="Few labels; pseudo-labels for pre-training", threat_type="Known and unknown CAN attacks",
        evaluation="F1 for known and unknown attacks", results="Unknown-attack F1 >0.9 (similar characteristics), 0.84 (different characteristics)",
        best_result="F1 >0.9 on unknown attacks", baseline="Baselines needing more labels", limitations=NR, future_work=NR,
        generalization="Unknown attacks with similar / different characteristics", real_world="Vehicle networks", explainability="None reported",
        reproducibility=NR, source_note=ABS, quality=q(2, 1, 1, 2, 1, 0, 0)),
    dict(  # 21
        title="Application of deep reinforcement learning to intrusion detection for supervised problems",
        authors="M. Lopez-Martin; B. Carro; A. Sanchez-Esguevillas", year=2020, venue="Expert Systems with Applications", publisher="Elsevier",
        quartile="Q1", sjr=1.854, ranking_source="SJR 2024 (Q1)", doi_url="Not retrieved (ESWA vol. 141, art. 112963)",
        problem="Applying DRL to labelled intrusion datasets", objective="Replace the environment with a sampling function over labelled data; compare DQN, DDQN, PG, AC",
        method="DRL (classification as RL)", model="DQN, DDQN, Policy Gradient, Actor-Critic", dataset="NSL-KDD; AWID", features="Flow / Wi-Fi frame features",
        labels="Fully labelled", threat_type="General intrusions (NSL-KDD), Wi-Fi attacks (AWID)", evaluation="Accuracy, F1, precision, recall",
        results=NR, best_result=NR, baseline="Classic ML and DL classifiers", limitations=NR, future_work=NR,
        generalization="Two datasets; no unseen-attack test", real_world=NR, explainability="None", reproducibility=NR, source_note=ABS, quality=q(2, 1, 1, 1, 2, 0, 0)),
    dict(  # 22
        title="Enhancing anomaly-based zero-day attack detection framework using CNN-driven feature extraction and OC-SVM",
        authors="Tripathy et al.", year=2026, venue="Scientific Reports", publisher="Nature Portfolio", quartile="Q1", sjr=0.874,
        ranking_source="SJR 2024, Multidisciplinary (Q1)", doi_url="https://pmc.ncbi.nlm.nih.gov/articles/PMC13527146/",
        problem="Signature IDS miss zero-day attacks", objective="CNN embeddings + One-Class SVM trained on benign traffic",
        method="Semi-supervised / one-class anomaly detection", model="1D-CNN feature extractor; OC-SVM (RBF)",
        dataset="NSL-KDD (37,130 records); CIC-IDS2017 (120,547 flows; Monday benign train, Friday attacks test)", features="41 / 80+ flow features",
        labels="Benign-only for OC-SVM; CNN trained on mixed data", threat_type="Port scan, botnet, DDoS (CIC-IDS2017); NSL-KDD attack classes",
        evaluation="Accuracy, precision, recall, F1", results="NSL-KDD 98.41% acc / 98.40% F1; CIC-IDS2017 99.31% acc / 99.11% F1",
        best_result="99.31% accuracy (CIC-IDS2017)", baseline="Isolation Forest, K-means, DBSCAN (with / without CNN features)",
        limitations="Limited training data; class imbalance; no real-time latency analysis", future_work="Hybrid / ensemble models; IoT and critical-infrastructure datasets; latency, pruning, quantisation",
        generalization="Unseen attack days (CIC-IDS2017)", real_world="No latency analysis", explainability="None",
        reproducibility="Code on Zenodo (10.5281/zenodo.19743083); public datasets", source_note="full text (PMC)", quality=q(2, 1, 1, 1, 2, 0, 2)),
]
for i, p in enumerate(papers, 1):
    p["id"] = i
    p.setdefault("best_result", NR)
    p["quality_total"] = sum(p["quality"].values())

excluded = [
    # preprint only
    *[dict(title=t, venue="arXiv", quartile="n/a", stage="Venue type", reason="preprint only, no journal version found") for t in [
        "SOUL: Semi-supervised Open-world continUal Learning for NIDS (arXiv 2412.00911)",
        "CITADEL: Continual Anomaly Detection for IoT Intrusion Detection (arXiv 2508.19450)",
        "ACORN-IDS: Adaptive Continual Novelty Detection for IDS (arXiv 2602.07291)",
        "ThreatFormer-IDS: Zero-Day Generalization and Explainable Attribution (arXiv 2603.00185)",
        "DeepXplain: XAI-Guided Autonomous Defense Against Multi-Stage APT (arXiv 2603.21296)",
        "UNAD+: Explainable Hybrid Framework for Unknown Network Attack Detection (arXiv 2605.22621)",
        "Navigating the Latent Manifold: Proactive Concept Drift Adaptation for NIDS (arXiv 2609.08623)",
        "Enhancing Autonomous Online IDS for IoT with Reliable Pseudo-Labels (arXiv 2605.26166)",
        "Probabilistic Robustness-driven UAPs with Explainability against DRL-based IDS (arXiv 2609.30605)",
        "Explainable Autonomous Cyber Defense using Adversarial MARL / C-MADF (arXiv 2604.04442)",
        "Robust Semi-Supervised Temporal Intrusion Detection (RSST-NIDS) (arXiv 2604.12655)",
        "AOC-IDS: Autonomous Online Framework with Contrastive Learning (arXiv 2402.01807)",
        "HuntGPT: ML anomaly detection + XAI + LLM (arXiv 2309.16021)",
    ]],
    # conference / chapter
    dict(title="Continual Learning with Strategic Selection and Forgetting (SSF)", venue="IEEE INFOCOM 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="ExpIDS: Drift-adaptable NIDS with Improved Explainability", venue="IEEE conference (Xplore 10815461)", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Replay or Regret: Evaluating Continual Learning Methods for Robust ID", venue="IEEE MILCOM 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Poster: SCL-IDS Semi-Supervised Continual Learning for Adaptive ID", venue="IEEE ICNP 2025", quartile="n/a", stage="Venue type", reason="poster"),
    dict(title="MAML AE-SAC: Meta-Learning and Adversarial RL for Adaptive ID", venue="KSE 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Q-ID: A Reinforcement Learning Framework for Adaptive Intrusion Detection", venue="FedCSIS 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Deep RL-Based IDS for Next-Generation Wireless Networks", venue="ICIRCA 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Network Anomaly Detection Using Q-Learning and Deep Q-Learning (UNSW-NB15 zero-day)", venue="ICSECS 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Detecting Zero-Day Attacks in Cloud Environments Using Adaptive DQN (ZDADS)", venue="ICCES 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Explainable Graph-based Reinforcement Learning for Intrusion Detection", venue="ICCMC 2025", quartile="n/a", stage="Venue type", reason="conference paper"),
    dict(title="Reinforcement Learning for Automated Intrusion Detection in Zero-Day Scenarios", venue="Book chapter (2025)", quartile="n/a", stage="Venue type", reason="book chapter"),
    dict(title="Online Framework for IDS with explainability-driven drift detector", venue="CEUR-WS Vol-4198", quartile="n/a", stage="Venue type", reason="workshop paper"),
    # rank
    dict(title="Continual Learning for Intrusion Detection Under Evolving Network Threats (Guo et al.)", venue="Future Internet", quartile="Q2", stage="Journal rank", reason="journal below Q1 (SJR 2024 Q2)"),
    dict(title="Post-Hoc Categorization Based on XAI and RL for Improved Intrusion Detection", venue="Applied Sciences", quartile="Q2", stage="Journal rank", reason="journal below Q1 (SJR 2024 Q2)"),
    dict(title="A Continual Learning Process to Detect Previously Learned and Newly Emerging Attacks (Memory-LGBM)", venue="Applied Sciences", quartile="Q2", stage="Journal rank", reason="journal below Q1 (SJR 2024 Q2)"),
    dict(title="A versatile XAI-based framework for efficient and explainable IDS", venue="Annals of Telecommunications", quartile="Q2", stage="Journal rank", reason="journal below Q1 (SJR 2024 Q2)"),
    dict(title="SpIDER: Satellite Intrusion Detection Using Explainable Reinforcement Learning", venue="Telecom (MDPI)", quartile="not verified", stage="Journal rank", reason="rank not verifiable / not Q1"),
    dict(title="Harnessing DBSCAN and auto-encoder for hyper intrusion detection in cloud computing", venue="Bulletin of Electrical Engineering and Informatics", quartile="not verified", stage="Journal rank", reason="rank not verifiable / not Q1"),
    # reviews / out of domain
    dict(title="Application of DRL for Intrusion Detection in IoT: A Systematic Review", venue="Internet of Things (Elsevier)", quartile="Q1", stage="Full text", reason="review (used for snowballing)"),
    dict(title="Evolving cybersecurity frontiers: survey on concept drift in IDS", venue="Engineering Applications of AI", quartile="Q1", stage="Full text", reason="survey (used for snowballing)"),
    dict(title="XAI-Guided Continual Learning: Rationale, Methods, and Future Directions", venue="WIREs Data Mining and Knowledge Discovery", quartile="not verified", stage="Full text", reason="review, outside IDS (evidence that XAI-guided CL exists outside security)"),
    dict(title="Explaining anomalies detected by autoencoders using SHAP (Antwarg et al.)", venue="Expert Systems with Applications", quartile="Q1", stage="Full text", reason="out of domain (not network traffic); methodological enabler for gap 1"),
]

gaps = [
    dict(axis="Method: four-way combination", covered="Pairs and triples exist: DRL + CL (1, 5, 10, 12), unsupervised + DRL (1, 8, 20), unsupervised + XAI (19), DRL + XAI (9).",
         missing="No included study combines unsupervised zero-day detection, DRL, continual learning and XAI.",
         evidence="0/22 papers have all four; 1/22 (GARDIAN) has three (no XAI)", papers="1, 8, 9, 19, 20"),
    dict(axis="Explainability", covered="SHAP used post hoc on a detector (9, 19).",
         missing="No study uses explanations inside the adaptation loop: to validate pseudo-labels, as DRL state, or to explain forgetting / drift.",
         evidence="2/22 report any XAI; 0/22 use XAI to drive or audit continual updates", papers="9, 19"),
    dict(axis="Label (pseudo-label quality)", covered="Pseudo-labels or distance-based labels for new traffic (1, 3, 8, 18, 20).",
         missing="Pseudo-label accuracy is rarely reported, and no study gates labels before retraining. Our GARDIAN reproduction: 82.5% correct Layer-1 labels made fine-tuning harmful.",
         evidence="5/22 auto-label new traffic; 0/5 report pseudo-label precision as a metric", papers="1, 3, 8, 18, 20"),
    dict(axis="DRL decision scope", covered="DRL as classifier (2, 5, 6, 7, 21), as sample selector (3, 20), as model/feature selector (4, 12), as retraining controller (1).",
         missing="Only GARDIAN lets DRL decide when and how much to retrain; its state holds only performance and buffer counts. No agent can roll back or veto an update.",
         evidence="1/22 uses DRL to control continual updates", papers="1, 3, 4, 5, 12"),
    dict(axis="Generalization / evaluation protocol", covered="Withheld-class zero-day splits (2, 3, 6, 8), cross-dataset (1, 8), long-horizon real traffic (5).",
         missing="Zero-day splits differ per paper; held-out sets often not listed (2); zero-day ground truth sometimes defined by the detector's own threshold (8).",
         evidence="2/22 cross-dataset; 1/22 multi-year real traffic", papers="1, 2, 5, 8"),
    dict(axis="Statistics / reproducibility", covered="Code or data released for 4/22 (1, 5, 6, 22).",
         missing="Seeds and variance almost never reported; the GARDIAN public code omits its Layer 1.",
         evidence="1/22 reports multi-run statistics (8); 4/22 release code or data", papers="1, 5, 6, 8, 22"),
    dict(axis="Data / feature representation", covered="Benchmarks: NSL-KDD, UNSW-NB15, CICIDS2017, CICIoT2023, NetFlow v2, UGRansome, MAWIFlow.",
         missing="No study examines how categorical encoding affects novelty detection; our UGRansome test shows label encoding hides unseen families (AUC 0.49) and one-hot reveals them (AUC 0.94).",
         evidence="0/22 analyse encoding vs novelty", papers="2"),
    dict(axis="Real-world", covered="Latency reported (8, 9, 11); 4-year real traffic (5).",
         missing="No deployment of an autonomous update loop; no analyst-in-the-loop evaluation of explanations.",
         evidence="1/22 uses real long-term traffic", papers="5, 8, 9, 11"),
]

opportunities = [
    dict(direction="Explanation-gated pseudo-labelling: admit an auto-labelled zero-day sample to retraining only when its attribution profile (SHAP on the autoencoder's reconstruction error, as in Antwarg et al.) agrees with its cluster's profile; report pseudo-label precision.",
         gaps="Explainability, Label, Method", papers="1, 8, 18, 20"),
    dict(direction="Explanation-aware DRL controller: add attribution-shift features to the agent's state and give it skip / rollback actions, so each retraining decision is justified and harmful updates are vetoed.",
         gaps="DRL decision scope, Explainability", papers="1, 4, 5, 9"),
    dict(direction="Explaining continual updates: compare classifier attributions before and after each update to detect forgetting or shortcut learning, and expose it to analysts.",
         gaps="Explainability, Real-world", papers="1, 13, 14"),
    dict(direction="Novelty-preserving encoding for zero-day ransomware: study categorical encoding (one-hot, embeddings) as a design factor for unsupervised detection, using UGRansome and NetFlow.",
         gaps="Data / feature representation, Generalization", papers="2, 22"),
    dict(direction="A shared zero-day continual-learning benchmark protocol: listed held-out families or classes, cross-dataset streams, pseudo-label metrics, multiple seeds, released code.",
         gaps="Generalization, Statistics / reproducibility", papers="1, 2, 5, 8"),
]

review = dict(topic="Zero-day intrusion detection with unsupervised learning + DRL + continual learning + XAI",
              search_date=D, protocol=protocol, prisma=prisma, papers=papers, excluded=excluded,
              gaps=gaps, opportunities=opportunities)
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "review.json")
json.dump(review, open(out, "w"), indent=2, ensure_ascii=False)
print("papers", len(papers), "excluded", len(excluded), "->", out)
